---
- name: create exoscale instance
  cs_instance:
    name: "{{ exoscaleConfig['name'] }}"
    template: "{{ exoscaleConfig['template'] }}"
    template_filter: "{{ exoscaleConfig['template_filter'] | default('executable') }}"
    zone: "{{ exoscaleConfig['zone'] }}"
    service_offering: "{{ exoscaleConfig['type'] }}"
    disk_size: "{{ exoscaleConfig['disk_size'] }}"
    ssh_key: "{{ exoscaleConfig['ssh_key'] }}"
    security_groups: "{{ exoscaleConfig['security_groups'] }}"
    api_key: "{{ exoscaleConfig['api_key'] }}"
    api_secret: "{{ exoscaleConfig['api_secret'] }}"
    api_url: "{{ exoscaleConfig['endpoint'] }}"
    user_data: |
      #cloud-config
      runcmd:|
        - echo xx > /root/x
  delegate_to: localhost
  register: exoscale_instance

- name: Register host for inventory
  add_host:
    name: "{{ exoscale_instance.default_ip }}"
    groups: [ default, common ]
    ansible_user: ubuntu
